version: '3'

services:
  app:
    build:
      context: .
      target: development
    ports:
      - '5010:5010'
    volumes:
      - .:/app
      - /app/node_modules
      - embeddings-data:/app/server

  test:
    build:
      context: .
      target: test
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  embeddings-data: